# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'RubikSolver-iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'OpenCV', '~> 3.1.0.1'
  pod 'CTAssetsPickerController'

end
